import React, { Component } from 'react'

export default class center extends Component {
  render () {
    const centerStyle = {
      backgroundColor: 'green',
      textAlign: 'center',
      color:'white'
    }
    return (
      <div style={centerStyle}>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
        <div>这是center</div>
      </div>
    )
  }
}
